wso2/docs-bi

- .github/workflows/publish_docs.yaml
- en/docs/index.md
- Add workflow to publish docs to Github pages
> Add workflow to publish docs

- en/mkdocs.yml
> Fix base_path

- en/docs/assets/css/image.css
- en/docs/roadmap/language-support.md
- en/docs/roadmap/roadmap.md
- en/mkdocs.yml
> Add roadmap docs

- README.md
> Update README.md with Kola

- en/docs/get-started/quick-start-guide.md
> Fix quick start guide

- en/docs/index.md
> Reduce text in home page

- en/docs/get-started/quick-start-guide.md
> Update duplicate heading

- en/docs/index.md
- en/docs/learn/message-routing.md
> Reduce texts in home page

- en/docs/learn/service-orchestration.md
> Fix image formatting

- en/docs/get-started/quick-start-guide.md
- en/docs/index.md
- en/mkdocs.yml
> Fix minor typos

- en/docs/learn/data-mapping.md
> Update Data Mapping guide with missing step

- en/docs/get-started/quick-start-guide.md
- Escape resource path in quick-start
> Escape resource path in quick-start

- en/docs/learn/service-orchestration.md
> Fix json outputs

- en/requirements.txt
- Update mkdocs-minify-plugin version
> Update mkdocs-minify-plugin version

- README.md
- en/docs/get-started/quick-start-guide.md
- en/docs/learn/message-transformation.md
- en/docs/learn/service-orchestration.md
- en/mkdocs.yml
- Update steps with UI changes
> Update steps with changes

- README.md
> Update access URL

- en/docs/learn/ai-agent-integration.md
- en/docs/learn/data-mapping.md
- en/mkdocs.yml
> $subject
Fixes: https://github.com/orgs/wso2/projects/123/views/8?pane=issue&itemId=104908448&issue=wso2%7Cproduct-ballerina-integrator%7C71
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
> Add AI Agent Learn Page

- en/mkdocs.yml
> Update base path

- en/docs/learn/ai-agent-integration.md
> Fix image rendering within Note block

- en/docs/learn/ai-agent-integration.md
> Update Agent Learn Page

- en/docs/CNAME
- Temporarily remove CNAME entry
> Temporarily remove CNAME entry

- en/docs/CNAME
> Revert "Temporarily remove CNAME entry"

- en/docs/learn/enterprise-integrations-patterns.md
- en/mkdocs.yml
> Add enterprise integrations patterns to BI documentation

- en/docs/learn/tools/mulesoft-migration-tool.md
- en/docs/learn/tools/tibco-businessworks-migration-tool.md
- en/mkdocs.yml
> Fix tool docs

- en/docs/learn/tools/tibco-businessworks-migration-tool.md
> Fix typo in TIBCO docs

- en/docs/learn/mulesoft-migration-tool.md
- en/docs/learn/tools/mulesoft-migration-tool.md
> Add example xml file migration to the `mulesoft-migration-tool.md`

- en/docs/learn/tools/tibco-businessworks-migration-tool.md
+ Update tibco docs example
+ Remove specific mention of the bwp extension (we support both bwp and process)
> Link to the PR for …
> Update TIBCO docs example

- en/docs/get-started/introduction.md
Fix review suggestions in https://github.com/wso2/docs-bi/pull/79/
> Fix typos in docs

- README.md
- en/mkdocs.yml
> Fix a typo and a link

- en/docs/index.md
Change Service Crchestration -> Service Orchestration
> Fix typo in home page

- README.md
> Fix a link in the README file

- en/docs/learn/tools/mulesoft-migration-tool.md
- en/docs/learn/tools/tibco-businessworks-migration-tool.md
> Add disclaimers for tool pages

- en/docs/learn/ai/rag/build-a-rag-application.md
- en/mkdocs.yml
This PR removes the usage of the word `pipeline` from the documentation. 
> Link to the PR for changes to the training content in …
> Remove the word 'pipeline' and apply minor improvements

- en/requirements.txt
This PR adds the `mkdocs-open-in-new-tab` plugin (version `1.0.3`) to `requirements.txt` to ensure consistent environment setup for MkDocs builds.
Added the following line to `requirements.txt`:
```
mkdocs-open-in-new-tab===1.0.3
```
> Link(s) to product documentation that addresses …
> Add mkdocs-open-in-new-tab plugin to requirements.txt

- en/docs/learn/ai/agents/index.md
- en/mkdocs.yml
> Add Agents Overview Page

- en/docs/learn/tools/tibco-businessworks-migration-tool.md
> Update TIBCO docs with BW 6 sample

- en/docs/developer-guides/tools/migration-tools/tibco-businessworks-migration-tool.md
> Update tibco docs to match 1.2.5

- en/docs/developer-guides/tools/migration-tools/mulesoft-migration-tool.md
> Update `migrate-mule` tool doc with latest changes

- en/docs/developer-guides/tools/migration-tools/logic-apps-migration-tool.md
> Update Logic Apps documentation

- en/docs/integration-guides/ai/agents/index.md
- en/docs/integration-guides/ai/agents/integrating-agents-with-mcp-servers.md
- en/mkdocs.yml
> Add docs for integrating AI agent with MCP servers

- en/docs/observability-and-monitoring/supported-observability-tools-and-platforms/opensearch.md
> Fix indentation issue in OpenSearch doc

- en/docs/developer-guides/tools/migration-tools/mulesoft-migration-tool.md
> Change sub-heading to sentence case in Mule migration tool docs

- en/docs/references/system-requirements.md
$subject
Based on the discussion https://github.com/wso2/docs-bi/pull/127#discussion_r2289796506
> Remove the DBMS section from system requirements

- .github/CODEOWNERS
> Update CODEOWNERS to include new owners
